# Generated by Django 3.1.1 on 2020-10-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedspace',
            old_name='bed_no',
            new_name='bed_number',
        ),
    ]
