# Generated by Django 3.1.1 on 2020-10-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
