# Generated by Django 3.1.1 on 2020-10-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
