# Generated by Django 3.1.1 on 2020-09-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200913_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lmaooo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
