# Generated by Django 3.1.1 on 2020-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201003_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
