# Generated by Django 3.1.1 on 2020-10-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201003_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedspace',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
