# Generated by Django 3.1.1 on 2020-10-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20201004_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
