# Generated by Django 3.1.1 on 2020-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201005_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
