# Generated by Django 3.1.1 on 2020-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_unit_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
