# Generated by Django 3.1.1 on 2020-10-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201006_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='unit_images'),
        ),
    ]
