# Generated by Django 3.1.1 on 2020-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='unit_images'),
        ),
    ]
