# Generated by Django 3.1.1 on 2020-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201007_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='unit_images'),
        ),
    ]
