# Generated by Django 3.1.1 on 2020-10-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201007_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
        migrations.CreateModel(
            name='Unit_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='unit_images')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management.unit')),
            ],
        ),
    ]
