# Generated by Django 3.1.1 on 2020-11-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201011_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='management.unit')),
            ],
        ),
    ]
